upgrade mysql package to mysql2
bitfinexcom/bfx-facs-db-mysql pull request #4
Opened 2024-03-22 16:15 UTC by grantfayvor

Old [`mysql`](https://www.npmjs.com/package/mysql) package does not support the new `caching_sha2_password` authentication mechanism introduced in MySQL version 8. Also, the old `mysql` package was last updated 4 years ago so it's unlikely that it is still a maintained package.

This PR switches to [`mysql2`](https://www.npmjs.com/package/mysql2) package which is more popular now and thankfully mostly maintains backwards-compatibility with the older `mysql` package. The APIs are the same for the most part and I've only noticed some minor differences in the events that are emitted between the two. For instance, while the older package emits a `close` event, the newer package emits `finish`. Still, for the most part, the events emitted are the same across both but it's noteworthy to watch out for it in our existing codebases.

2024-03-24 01:31 UTC, ezewer approved these changes
Looks good to me!

2024-03-24 08:15 UTC, face approved these changes

2024-03-25 09:34 UTC, vigan-abd requested changes

2024-03-25 09:34 UTC, vigan-abd commented on test/unit.js
>        await sleep(1000)
getting this error on tests:
```
  1) DbFacility tests
       queryStream tests
         should not fetch new rows unless requested by iterator:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

2 !== 1

      + expected - actual

      -2
      +1
      
      at Context.<anonymous> (test/unit.js:471:14)
```

2024-03-25 10:58 UTC, vigan-abd requested changes

2024-03-25 10:58 UTC, vigan-abd commented on test/unit.js
> +      closeCalls = calls.filter(x => ['finish', 'close'].includes(x[0]))
```suggestion
      closeCalls = calls.filter(x => x[0] === 'finish')
```

2024-03-25 11:09 UTC, ezewer approved these changes
lgtm!

2024-03-25 11:35 UTC, vigan-abd approved these changes

2024-03-25 11:47 UTC, merged